# Generated by Django 3.2.20 on 2023-08-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledRebalancing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=255)),
                (
                    "with_respect_to",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="PK of the respected object.",
                        max_length=255,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
